INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY1", createdAt=now();
insert into contestants set name="HARMONIC KINGS" ,electionID=5 ,categoryID=1 ,code="1GRPY1", createdAt=now();
INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY2", createdAt=now();
insert into contestants set name="FOREVER MOTO BAND" ,electionID=5 ,categoryID=1 ,code="1GRPY2", createdAt=now();
INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY3", createdAt=now();
insert into contestants set name="SOVEREIGN GROUP" ,electionID=5 ,categoryID=1 ,code="1GRPY3", createdAt=now();
INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY4", createdAt=now();
insert into contestants set name="FATHERS HEART" ,electionID=5 ,categoryID=1 ,code="1GRPY4", createdAt=now();
INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY5", createdAt=now();
insert into contestants set name="VOICE CHORD" ,electionID=5 ,categoryID=1 ,code="1GRPY5", createdAt=now();
INSERT INTO categories SET name="GROUP OF THE YEAR" ,electionID=5 ,categoryID=1 ,code="1GRPY6", createdAt=now();
insert into contestants set name="SENTIVILLE MELODIES" ,electionID=5 ,categoryID=1 ,code="1GRPY6", createdAt=now();
INSERT INTO categories SET name="HIP-HOP SONG OF THE YEAR" ,electionID=5 ,categoryID=2 ,code="2HPSY1", createdAt=now();
insert into contestants set name="LIBRA ONE    - AJABU" ,electionID=5 ,categoryID=2 ,code="2HPSY1", createdAt=now();
INSERT INTO categories SET name="HIP-HOP SONG OF THE YEAR" ,electionID=5 ,categoryID=2 ,code="2HPSY2", createdAt=now();
insert into contestants set name="RAP KING COLLO  - AMEN" ,electionID=5 ,categoryID=2 ,code="2HPSY2", createdAt=now();
INSERT INTO categories SET name="HIP-HOP SONG OF THE YEAR" ,electionID=5 ,categoryID=2 ,code="2HPSY3", createdAt=now();
insert into contestants set name="SOVEREIGN  - CHRIST A DE BEST" ,electionID=5 ,categoryID=2 ,code="2HPSY3", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY1", createdAt=now();
insert into contestants set name="SHIRLEEN VOBIC" ,electionID=5 ,categoryID=3 ,code="3YTY1", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY2", createdAt=now();
insert into contestants set name="PRAISE MAKENA" ,electionID=5 ,categoryID=3 ,code="3YTY2", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY3", createdAt=now();
insert into contestants set name="WHITNEY JOY" ,electionID=5 ,categoryID=3 ,code="3YTY3", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY4", createdAt=now();
insert into contestants set name="JOY ANNA" ,electionID=5 ,categoryID=3 ,code="3YTY4", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY5", createdAt=now();
insert into contestants set name="LYNN BAHATI" ,electionID=5 ,categoryID=3 ,code="3YTY5", createdAt=now();
INSERT INTO categories SET name="YOUNG TALENT OF THE YEAR" ,electionID=5 ,categoryID=3 ,code="3YTY6", createdAt=now();
insert into contestants set name="NENKAI" ,electionID=5 ,categoryID=3 ,code="3YTY6", createdAt=now();
INSERT INTO categories SET name="RADIO PRESENTER OF THE YEAR" ,electionID=5 ,categoryID=4 ,code="4RPY1", createdAt=now();
insert into contestants set name="MC WAYNE - TANDAZA RADIO" ,electionID=5 ,categoryID=4 ,code="4RPY1", createdAt=now();
INSERT INTO categories SET name="RADIO PRESENTER OF THE YEAR" ,electionID=5 ,categoryID=4 ,code="4RPY2", createdAt=now();
insert into contestants set name="MTUME PAUL MUCHESI   –  RADIO YETU" ,electionID=5 ,categoryID=4 ,code="4RPY2", createdAt=now();
INSERT INTO categories SET name="RADIO PRESENTER OF THE YEAR" ,electionID=5 ,categoryID=4 ,code="4RPY3", createdAt=now();
insert into contestants set name="MAGDALENA MSUPA WA YESU - RADIO AMANI" ,electionID=5 ,categoryID=4 ,code="4RPY3", createdAt=now();
INSERT INTO categories SET name="RADIO PRESENTER OF THE YEAR" ,electionID=5 ,categoryID=4 ,code="4RPY4", createdAt=now();
insert into contestants set name="KAGZ      - MBCI RADIO" ,electionID=5 ,categoryID=4 ,code="4RPY4", createdAt=now();
INSERT INTO categories SET name="RADIO PRESENTER OF THE YEAR" ,electionID=5 ,categoryID=4 ,code="4RPY5", createdAt=now();
insert into contestants set name="SAMSON SIMPIRI    -  SIDAI FM" ,electionID=5 ,categoryID=4 ,code="4RPY5", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY1", createdAt=now();
insert into contestants set name="IRENE SEUREY ft. TOQCIE  - MAWALAKSEI" ,electionID=5 ,categoryID=5 ,code="5CSY1", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY2", createdAt=now();
insert into contestants set name="ZAE DE KIM ft. G-NICE - WACHA IWE" ,electionID=5 ,categoryID=5 ,code="5CSY2", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY3", createdAt=now();
insert into contestants set name="TERRY K ft. PAUL GATUNE - KIRATHIMO" ,electionID=5 ,categoryID=5 ,code="5CSY3", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY4", createdAt=now();
insert into contestants set name="HECH KENYA ft. ELMOH - SINA NOMA" ,electionID=5 ,categoryID=5 ,code="5CSY4", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY5", createdAt=now();
insert into contestants set name="SINQOLO ft. TONY KABALA - SYSTEM YA FIRE" ,electionID=5 ,categoryID=5 ,code="5CSY5", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY6", createdAt=now();
insert into contestants set name="PAUL GATUNE ft. JOSEPH Y - NGAI WA MWENA WAKWA" ,electionID=5 ,categoryID=5 ,code="5CSY6", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY7", createdAt=now();
insert into contestants set name="MC TITOH, PASHA TRUTH& MBENJA - MOST HIGH" ,electionID=5 ,categoryID=5 ,code="5CSY7", createdAt=now();
INSERT INTO categories SET name="COLLABORATION SONG OF THE YEAR" ,electionID=5 ,categoryID=5 ,code="5CSY8", createdAt=now();
insert into contestants set name="JAY DONGA ft MASTERPIECE - NIKKI NIKKI" ,electionID=5 ,categoryID=5 ,code="5CSY8", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY1", createdAt=now();
insert into contestants set name="MAUREEN KESILET    - MOYO WANGU" ,electionID=5 ,categoryID=6 ,code="6WSY1", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY2", createdAt=now();
insert into contestants set name="DAN WADHAMANA   - NASHUKA" ,electionID=5 ,categoryID=6 ,code="6WSY2", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY3", createdAt=now();
insert into contestants set name="BROTHER JACKSON MUSIC  - BABA SISI TUNASONGEA" ,electionID=5 ,categoryID=6 ,code="6WSY3", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY4", createdAt=now();
insert into contestants set name="MAMA KINGS    - WEWE NI MUNGU" ,electionID=5 ,categoryID=6 ,code="6WSY4", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY5", createdAt=now();
insert into contestants set name="VERONICAH ATIENO   - KUTEMBEA NA YESU" ,electionID=5 ,categoryID=6 ,code="6WSY5", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY6", createdAt=now();
insert into contestants set name="RUTH NDIEMA    - WORTHY" ,electionID=5 ,categoryID=6 ,code="6WSY6", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY7", createdAt=now();
insert into contestants set name="TABBY PRAISE    - YOU ARE SO GOOD" ,electionID=5 ,categoryID=6 ,code="6WSY7", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY8", createdAt=now();
insert into contestants set name="LETAIYAN OLEIGERO   - NIKUABUDU" ,electionID=5 ,categoryID=6 ,code="6WSY8", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY9", createdAt=now();
insert into contestants set name="ANNE BLESSED    - MOYO WANGU" ,electionID=5 ,categoryID=6 ,code="6WSY9", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY10", createdAt=now();
insert into contestants set name="FRANK ASAPH    - NAFSI YANGU" ,electionID=5 ,categoryID=6 ,code="6WSY10", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY11", createdAt=now();
insert into contestants set name="FAITH NDUHIU    - UKUU WA MUNGU" ,electionID=5 ,categoryID=6 ,code="6WSY11", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY12", createdAt=now();
insert into contestants set name="GODWIL BABETTE    - TUNAKUSUJUDU" ,electionID=5 ,categoryID=6 ,code="6WSY12", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY13", createdAt=now();
insert into contestants set name="JEFF WALLACE    -  JE WEWE?" ,electionID=5 ,categoryID=6 ,code="6WSY13", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY14", createdAt=now();
insert into contestants set name="CATE MBUGUA    - MWAMINIFU" ,electionID=5 ,categoryID=6 ,code="6WSY14", createdAt=now();
INSERT INTO categories SET name="WORSHIP SONG OF THE YEAR" ,electionID=5 ,categoryID=6 ,code="6WSY15", createdAt=now();
insert into contestants set name="MIMAH SHAFFIE    - NI WEWE" ,electionID=5 ,categoryID=6 ,code="6WSY15", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY1", createdAt=now();
insert into contestants set name="KINGRED HOPE" ,electionID=5 ,categoryID=7 ,code="7HMY1", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY2", createdAt=now();
insert into contestants set name="HYPEKING DTO" ,electionID=5 ,categoryID=7 ,code="7HMY2", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY3", createdAt=now();
insert into contestants set name="MC SHIZE" ,electionID=5 ,categoryID=7 ,code="7HMY3", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY4", createdAt=now();
insert into contestants set name="HYPEMAN DOMMY" ,electionID=5 ,categoryID=7 ,code="7HMY4", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY5", createdAt=now();
insert into contestants set name="HYPE COLLO" ,electionID=5 ,categoryID=7 ,code="7HMY5", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY6", createdAt=now();
insert into contestants set name="MC SOUJA" ,electionID=5 ,categoryID=7 ,code="7HMY6", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY7", createdAt=now();
insert into contestants set name="HYPEMAN BANZU" ,electionID=5 ,categoryID=7 ,code="7HMY7", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY8", createdAt=now();
insert into contestants set name="HYPE WILLY" ,electionID=5 ,categoryID=7 ,code="7HMY8", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY9", createdAt=now();
insert into contestants set name="HYPE VIGILANTE" ,electionID=5 ,categoryID=7 ,code="7HMY9", createdAt=now();
INSERT INTO categories SET name="HYPE MAN OF THE YEAR" ,electionID=5 ,categoryID=7 ,code="7HMY10", createdAt=now();
insert into contestants set name="MC TITOH" ,electionID=5 ,categoryID=7 ,code="7HMY10", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY1", createdAt=now();
insert into contestants set name="DAVE JESS - STEP UP GOSPEL SHOW" ,electionID=5 ,categoryID=8 ,code="8MDY1", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY2", createdAt=now();
insert into contestants set name="WAMBUGU WA WAIRIMU TRIPPLE W  - THAYU FM" ,electionID=5 ,categoryID=8 ,code="8MDY2", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY3", createdAt=now();
insert into contestants set name="DJ PANKRAZ (MY GENERATION MY ASSIGNMENT)" ,electionID=5 ,categoryID=8 ,code="8MDY3", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY4", createdAt=now();
insert into contestants set name="REVEREND DAD - ELDORET" ,electionID=5 ,categoryID=8 ,code="8MDY4", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY5", createdAt=now();
insert into contestants set name="SUPA WARUI   -  MBCI" ,electionID=5 ,categoryID=8 ,code="8MDY5", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY6", createdAt=now();
insert into contestants set name="WILSON KAMITI  - MBCI TV" ,electionID=5 ,categoryID=8 ,code="8MDY6", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY7", createdAt=now();
insert into contestants set name="OGOLA MJOMBA  - RADIO YETU" ,electionID=5 ,categoryID=8 ,code="8MDY7", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY8", createdAt=now();
insert into contestants set name="SAMSON SIMPIRI  - SIDAI FM" ,electionID=5 ,categoryID=8 ,code="8MDY8", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY9", createdAt=now();
insert into contestants set name="MC EMOS - MC EMOS OCLOCK" ,electionID=5 ,categoryID=8 ,code="8MDY9", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY10", createdAt=now();
insert into contestants set name="ESTELLE MWAI - NAKURU TV" ,electionID=5 ,categoryID=8 ,code="8MDY10", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY11", createdAt=now();
insert into contestants set name="KATE VOBIC - HERO RADIO" ,electionID=5 ,categoryID=8 ,code="8MDY11", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY12", createdAt=now();
insert into contestants set name="JOHN KAGO - VBN NETWORKS" ,electionID=5 ,categoryID=8 ,code="8MDY12", createdAt=now();
INSERT INTO categories SET name="MEDIA PERSONALITY OF THE YEAR" ,electionID=5 ,categoryID=8 ,code="8MDY13", createdAt=now();
insert into contestants set name="SARSHA - OCCUPY TV" ,electionID=5 ,categoryID=8 ,code="8MDY13", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY1", createdAt=now();
insert into contestants set name="STEP UP GOSPEL SHOW - STEP UP TV" ,electionID=5 ,categoryID=9 ,code="9TVSY1", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY2", createdAt=now();
insert into contestants set name="NBYM SHOW     - NAROK BAPTIST" ,electionID=5 ,categoryID=9 ,code="9TVSY2", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY3", createdAt=now();
insert into contestants set name="CROSS CONNECT - OCCUPY TV" ,electionID=5 ,categoryID=9 ,code="9TVSY3", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY4", createdAt=now();
insert into contestants set name="PRAISE AVENUE    - VBN" ,electionID=5 ,categoryID=9 ,code="9TVSY4", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY5", createdAt=now();
insert into contestants set name="SABALKHERI     - MBCI" ,electionID=5 ,categoryID=9 ,code="9TVSY5", createdAt=now();
INSERT INTO categories SET name="TV SHOWS OF THE YEAR" ,electionID=5 ,categoryID=9 ,code="9TVSY6", createdAt=now();
insert into contestants set name="MY GENERATION MY ASSIGNMENT - ONLINE" ,electionID=5 ,categoryID=9 ,code="9TVSY6", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY1", createdAt=now();
insert into contestants set name="IBADA YETU    - RADIO YETU" ,electionID=5 ,categoryID=10 ,code="10RDSY1", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY2", createdAt=now();
insert into contestants set name="GOSPEL DRIVE   - SAYARE RADIO" ,electionID=5 ,categoryID=10 ,code="10RDSY2", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY3", createdAt=now();
insert into contestants set name="SATURDAY NIGHT LIVE  - SAYARE RADIO" ,electionID=5 ,categoryID=10 ,code="10RDSY3", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY4", createdAt=now();
insert into contestants set name="VIBE SHOW    - MBCI" ,electionID=5 ,categoryID=10 ,code="10RDSY4", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY5", createdAt=now();
insert into contestants set name="ENKISISA    -  SIDAI FM" ,electionID=5 ,categoryID=10 ,code="10RDSY5", createdAt=now();
INSERT INTO categories SET name="RADIO SHOW OF THE YEAR" ,electionID=5 ,categoryID=10 ,code="10RDSY6", createdAt=now();
insert into contestants set name="KWIREKERERIA SHOW - THAYU FM" ,electionID=5 ,categoryID=10 ,code="10RDSY6", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY1", createdAt=now();
insert into contestants set name="SHADUFF MELODY - ORIGINAL" ,electionID=5 ,categoryID=11 ,code="11RGSY1", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY2", createdAt=now();
insert into contestants set name="MG DEZNAH - ROHO JUU" ,electionID=5 ,categoryID=11 ,code="11RGSY2", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY3", createdAt=now();
insert into contestants set name="HYPER JAMAL - BABA YAO" ,electionID=5 ,categoryID=11 ,code="11RGSY3", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY4", createdAt=now();
insert into contestants set name="BRIGEDIER SHILOH - I WORSHIP YOU" ,electionID=5 ,categoryID=11 ,code="11RGSY4", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY5", createdAt=now();
insert into contestants set name="G-BWOY - REAL FRIEND" ,electionID=5 ,categoryID=11 ,code="11RGSY5", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY6", createdAt=now();
insert into contestants set name="KALLY B    - BLESS ME" ,electionID=5 ,categoryID=11 ,code="11RGSY6", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY7", createdAt=now();
insert into contestants set name="ANGEL KENYA - CHAMPE" ,electionID=5 ,categoryID=11 ,code="11RGSY7", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY8", createdAt=now();
insert into contestants set name="COOPER COOPER   - HONORABLE" ,electionID=5 ,categoryID=11 ,code="11RGSY8", createdAt=now();
INSERT INTO categories SET name="REGGEA SONG OF THE YEAR" ,electionID=5 ,categoryID=11 ,code="11RGSY9", createdAt=now();
insert into contestants set name="FLOYD BELIEVER   - EASY" ,electionID=5 ,categoryID=11 ,code="11RGSY9", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY1", createdAt=now();
insert into contestants set name="MAUREEN KESILET" ,electionID=5 ,categoryID=12 ,code="12SWY1", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY2", createdAt=now();
insert into contestants set name="ZAWADI IBRAHIM" ,electionID=5 ,categoryID=12 ,code="12SWY2", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY3", createdAt=now();
insert into contestants set name="BARAK ESPAR" ,electionID=5 ,categoryID=12 ,code="12SWY3", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY4", createdAt=now();
insert into contestants set name="ANDY JOE" ,electionID=5 ,categoryID=12 ,code="12SWY4", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY5", createdAt=now();
insert into contestants set name="REUBEN KIGAME" ,electionID=5 ,categoryID=12 ,code="12SWY5", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY6", createdAt=now();
insert into contestants set name="MIKE LEBO MUSIC" ,electionID=5 ,categoryID=12 ,code="12SWY6", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY7", createdAt=now();
insert into contestants set name="OCHI PRAIZE" ,electionID=5 ,categoryID=12 ,code="12SWY7", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY8", createdAt=now();
insert into contestants set name="ABBY BAHATI" ,electionID=5 ,categoryID=12 ,code="12SWY8", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY9", createdAt=now();
insert into contestants set name="ROONEY MAX" ,electionID=5 ,categoryID=12 ,code="12SWY9", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY10", createdAt=now();
insert into contestants set name="TIMAM EVANS" ,electionID=5 ,categoryID=12 ,code="12SWY10", createdAt=now();
INSERT INTO categories SET name="SONG WRITER OF THE YEAR" ,electionID=5 ,categoryID=12 ,code="12SWY11", createdAt=now();
insert into contestants set name="GIDDY VIBEZ" ,electionID=5 ,categoryID=12 ,code="12SWY11", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY1", createdAt=now();
insert into contestants set name="KENAJ MUSIC    - SHINE" ,electionID=5 ,categoryID=13 ,code="13SY1", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY2", createdAt=now();
insert into contestants set name="IRENE SEUREY  - MAWALAKSEI" ,electionID=5 ,categoryID=13 ,code="13SY2", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY3", createdAt=now();
insert into contestants set name="ZAE DE KIM ft. GNICE - WACHA IWE" ,electionID=5 ,categoryID=13 ,code="13SY3", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY4", createdAt=now();
insert into contestants set name="SHARON RETOE  - ENDA NAMI" ,electionID=5 ,categoryID=13 ,code="13SY4", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY5", createdAt=now();
insert into contestants set name="FLOYD BELIEVER  - MOYO GWANGE" ,electionID=5 ,categoryID=13 ,code="13SY5", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY6", createdAt=now();
insert into contestants set name="MR. CHAIRMAN 254  - AMEKUA KWANGU" ,electionID=5 ,categoryID=13 ,code="13SY6", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY7", createdAt=now();
insert into contestants set name="FAITH NDUHIU  - UKUU WA MUNGU" ,electionID=5 ,categoryID=13 ,code="13SY7", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY8", createdAt=now();
insert into contestants set name="ANTONY MUSEMBI  - KUONGOZWA" ,electionID=5 ,categoryID=13 ,code="13SY8", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY9", createdAt=now();
insert into contestants set name="LENNY LION   - BOMBA" ,electionID=5 ,categoryID=13 ,code="13SY9", createdAt=now();
INSERT INTO categories SET name="SONG OF THE YEAR" ,electionID=5 ,categoryID=13 ,code="13SY10", createdAt=now();
insert into contestants set name="EVELYN WANJIRU  - NO ONE LIKE YOU" ,electionID=5 ,categoryID=13 ,code="13SY10", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY1", createdAt=now();
insert into contestants set name="KENAJ MUSIC    - SHINE" ,electionID=5 ,categoryID=14 ,code="14VDY1", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY2", createdAt=now();
insert into contestants set name="BRIGADIER SHILOH   - NAME OF JESUS" ,electionID=5 ,categoryID=14 ,code="14VDY2", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY3", createdAt=now();
insert into contestants set name="ZAE DE KIM ft. GNICE  - WACHA IWE" ,electionID=5 ,categoryID=14 ,code="14VDY3", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY4", createdAt=now();
insert into contestants set name="HECH KENYA    - SINA NOMA" ,electionID=5 ,categoryID=14 ,code="14VDY4", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY5", createdAt=now();
insert into contestants set name="PAPA TOMASO   - MWACHIE YESU" ,electionID=5 ,categoryID=14 ,code="14VDY5", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY6", createdAt=now();
insert into contestants set name="SHARON RETOE   - ENDA NAMI" ,electionID=5 ,categoryID=14 ,code="14VDY6", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY7", createdAt=now();
insert into contestants set name="MIKE LEBO    - SHUMATA" ,electionID=5 ,categoryID=14 ,code="14VDY7", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY8", createdAt=now();
insert into contestants set name="FLOYD BELIEVER   - MOYO GWANGE" ,electionID=5 ,categoryID=14 ,code="14VDY8", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY9", createdAt=now();
insert into contestants set name="MR. CHAIRMAN 254   - AMEKUA KWAMGU" ,electionID=5 ,categoryID=14 ,code="14VDY9", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY10", createdAt=now();
insert into contestants set name="REV. ANTONY MUSEMBI  - KUONGOZWA" ,electionID=5 ,categoryID=14 ,code="14VDY10", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY11", createdAt=now();
insert into contestants set name="LENNY LION    - ORWA" ,electionID=5 ,categoryID=14 ,code="14VDY11", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY12", createdAt=now();
insert into contestants set name="MERCY SONN    - UTAKUA NAMI" ,electionID=5 ,categoryID=14 ,code="14VDY12", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY13", createdAt=now();
insert into contestants set name="JECINTA KIBUKU   - NINGWENDETE" ,electionID=5 ,categoryID=14 ,code="14VDY13", createdAt=now();
INSERT INTO categories SET name="VIDEO OF THE YEAR" ,electionID=5 ,categoryID=14 ,code="14VDY14", createdAt=now();
insert into contestants set name="JAY DONGA       -CHOGIOGIO" ,electionID=5 ,categoryID=14 ,code="14VDY14", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY1", createdAt=now();
insert into contestants set name="TRIZAH DAN" ,electionID=5 ,categoryID=15 ,code="15NWY1", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY2", createdAt=now();
insert into contestants set name="HADASSAH" ,electionID=5 ,categoryID=15 ,code="15NWY2", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY3", createdAt=now();
insert into contestants set name="MG DEZNAH" ,electionID=5 ,categoryID=15 ,code="15NWY3", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY4", createdAt=now();
insert into contestants set name="KENNIWAN" ,electionID=5 ,categoryID=15 ,code="15NWY4", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY5", createdAt=now();
insert into contestants set name="ASHTIV" ,electionID=5 ,categoryID=15 ,code="15NWY5", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY6", createdAt=now();
insert into contestants set name="BRIGADIER SHILOH" ,electionID=5 ,categoryID=15 ,code="15NWY6", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY7", createdAt=now();
insert into contestants set name="P.K. HAKEEM" ,electionID=5 ,categoryID=15 ,code="15NWY7", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY8", createdAt=now();
insert into contestants set name="CAROL BETA" ,electionID=5 ,categoryID=15 ,code="15NWY8", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY9", createdAt=now();
insert into contestants set name="JOMBANASTIC" ,electionID=5 ,categoryID=15 ,code="15NWY9", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY10", createdAt=now();
insert into contestants set name="FLORENCE WEKESA" ,electionID=5 ,categoryID=15 ,code="15NWY10", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY11", createdAt=now();
insert into contestants set name="VERONICA ATIENO" ,electionID=5 ,categoryID=15 ,code="15NWY11", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY12", createdAt=now();
insert into contestants set name="SIMPOZZ" ,electionID=5 ,categoryID=15 ,code="15NWY12", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY13", createdAt=now();
insert into contestants set name="AJAS MICHAEL" ,electionID=5 ,categoryID=15 ,code="15NWY13", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY14", createdAt=now();
insert into contestants set name="SAM MANGA" ,electionID=5 ,categoryID=15 ,code="15NWY14", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY15", createdAt=now();
insert into contestants set name="TONY DA BLESSED KID" ,electionID=5 ,categoryID=15 ,code="15NWY15", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY16", createdAt=now();
insert into contestants set name="RESIAN LEPERES" ,electionID=5 ,categoryID=15 ,code="15NWY16", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY17", createdAt=now();
insert into contestants set name="G-BWOY" ,electionID=5 ,categoryID=15 ,code="15NWY17", createdAt=now();
INSERT INTO categories SET name="NEW ARTIST OF THE YEAR" ,electionID=5 ,categoryID=15 ,code="15NWY18", createdAt=now();
insert into contestants set name="SUSAN NDUNG’U" ,electionID=5 ,categoryID=15 ,code="15NWY18", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY1", createdAt=now();
insert into contestants set name="AFLEWO NAKURU" ,electionID=5 ,categoryID=16 ,code="16PRWTY1", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY2", createdAt=now();
insert into contestants set name="PACATO WORSHIP TEAM    - JCC NAKURU" ,electionID=5 ,categoryID=16 ,code="16PRWTY2", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY3", createdAt=now();
insert into contestants set name="KSF CHOIR      - KINGDOM SEEKERS" ,electionID=5 ,categoryID=16 ,code="16PRWTY3", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY4", createdAt=now();
insert into contestants set name="ONE ACCORD     - DELIVERANCE LCC" ,electionID=5 ,categoryID=16 ,code="16PRWTY4", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY5", createdAt=now();
insert into contestants set name="INTERNATIONAL VISION CENTRE (IVC)  - ELDORET" ,electionID=5 ,categoryID=16 ,code="16PRWTY5", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY6", createdAt=now();
insert into contestants set name="NAROK BAPTIST PRAISE & WORSHIP  - NAROK" ,electionID=5 ,categoryID=16 ,code="16PRWTY6", createdAt=now();
INSERT INTO categories SET name="PRAISE AND WORSHIP TEAM OF THE YEAR" ,electionID=5 ,categoryID=16 ,code="16PRWTY7", createdAt=now();
insert into contestants set name="FATHERS HEART" ,electionID=5 ,categoryID=16 ,code="16PRWTY7", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY1", createdAt=now();
insert into contestants set name="DJ MO ANGEL KENYA" ,electionID=5 ,categoryID=17 ,code="17DJY1", createdAt=now();
INSERT INTO categories SET name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
insert into contestants set name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
INSERT INTO categories SET name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
insert into contestants set name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
INSERT INTO categories SET name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
insert into contestants set name="" ,electionID=5 ,categoryID= ,code="", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY2", createdAt=now();
insert into contestants set name="DJ LAU SPIKID" ,electionID=5 ,categoryID=17 ,code="17DJY2", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY3", createdAt=now();
insert into contestants set name="DJ QUPE" ,electionID=5 ,categoryID=17 ,code="17DJY3", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY4", createdAt=now();
insert into contestants set name="DJ VINDEKS" ,electionID=5 ,categoryID=17 ,code="17DJY4", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY5", createdAt=now();
insert into contestants set name="DJ TRIKIDEH" ,electionID=5 ,categoryID=17 ,code="17DJY5", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY6", createdAt=now();
insert into contestants set name="DJ 2STE" ,electionID=5 ,categoryID=17 ,code="17DJY6", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY7", createdAt=now();
insert into contestants set name="DJ STAN" ,electionID=5 ,categoryID=17 ,code="17DJY7", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY8", createdAt=now();
insert into contestants set name="DJ WORSHIP" ,electionID=5 ,categoryID=17 ,code="17DJY8", createdAt=now();
INSERT INTO categories SET name="DJ OF THE YEAR" ,electionID=5 ,categoryID=17 ,code="17DJY9", createdAt=now();
insert into contestants set name="DJ TIU" ,electionID=5 ,categoryID=17 ,code="17DJY9", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC1", createdAt=now();
insert into contestants set name="MC ALEX MBURU NJOROGE (TOCHI YA MAWE)" ,electionID=5 ,categoryID=18 ,code="18MC1", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC2", createdAt=now();
insert into contestants set name="MC WAYNE" ,electionID=5 ,categoryID=18 ,code="18MC2", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC3", createdAt=now();
insert into contestants set name="MC TOTO MOSE" ,electionID=5 ,categoryID=18 ,code="18MC3", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC4", createdAt=now();
insert into contestants set name="MC DTO" ,electionID=5 ,categoryID=18 ,code="18MC4", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC5", createdAt=now();
insert into contestants set name="MC ERICK MUNTET" ,electionID=5 ,categoryID=18 ,code="18MC5", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC6", createdAt=now();
insert into contestants set name="MC KIPTABUT" ,electionID=5 ,categoryID=18 ,code="18MC6", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC7", createdAt=now();
insert into contestants set name="MC EVANS KENYA" ,electionID=5 ,categoryID=18 ,code="18MC7", createdAt=now();
INSERT INTO categories SET name="MC OF THE YEAR" ,electionID=5 ,categoryID=18 ,code="18MC8", createdAt=now();
insert into contestants set name="MC CIDDY" ,electionID=5 ,categoryID=18 ,code="18MC8", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY1", createdAt=now();
insert into contestants set name="ALMASI VOICES" ,electionID=5 ,categoryID=19 ,code="19CHRY1", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY2", createdAt=now();
insert into contestants set name="ST. JOSEPH THE WORKER CATHOLIC CHURCH -RACECOURSE" ,electionID=5 ,categoryID=19 ,code="19CHRY2", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY3", createdAt=now();
insert into contestants set name="ELIMU SDA YOUTH CHOIR" ,electionID=5 ,categoryID=19 ,code="19CHRY3", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY4", createdAt=now();
insert into contestants set name="AIC BONDENI" ,electionID=5 ,categoryID=19 ,code="19CHRY4", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY5", createdAt=now();
insert into contestants set name="SDA NAKURU CENTRAL" ,electionID=5 ,categoryID=19 ,code="19CHRY5", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY6", createdAt=now();
insert into contestants set name="AIC MILIMANI    - NAKURU" ,electionID=5 ,categoryID=19 ,code="19CHRY6", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY7", createdAt=now();
insert into contestants set name="P.A.G.     - LANET" ,electionID=5 ,categoryID=19 ,code="19CHRY7", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY8", createdAt=now();
insert into contestants set name="FRIENDS QUAKERS" ,electionID=5 ,categoryID=19 ,code="19CHRY8", createdAt=now();
INSERT INTO categories SET name="CHOIR OF THE YEAR" ,electionID=5 ,categoryID=19 ,code="19CHRY9", createdAt=now();
insert into contestants set name="FRIENDS QUAKERS  - AFRAHA" ,electionID=5 ,categoryID=19 ,code="19CHRY9", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY1", createdAt=now();
insert into contestants set name="TABBY NDI" ,electionID=5 ,categoryID=20 ,code="20FARY1", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY2", createdAt=now();
insert into contestants set name="TERRY K." ,electionID=5 ,categoryID=20 ,code="20FARY2", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY3", createdAt=now();
insert into contestants set name="SHARON RETOE" ,electionID=5 ,categoryID=20 ,code="20FARY3", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY4", createdAt=now();
insert into contestants set name="CHARITY NASHIPAI" ,electionID=5 ,categoryID=20 ,code="20FARY4", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY5", createdAt=now();
insert into contestants set name="UNIQUE WANJIKU" ,electionID=5 ,categoryID=20 ,code="20FARY5", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY6", createdAt=now();
insert into contestants set name="FAITH NDUHIU" ,electionID=5 ,categoryID=20 ,code="20FARY6", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY7", createdAt=now();
insert into contestants set name="CAROL B." ,electionID=5 ,categoryID=20 ,code="20FARY7", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY8", createdAt=now();
insert into contestants set name="ROSE CHEBOI" ,electionID=5 ,categoryID=20 ,code="20FARY8", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY9", createdAt=now();
insert into contestants set name="JOYNESS KILEO" ,electionID=5 ,categoryID=20 ,code="20FARY9", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY10", createdAt=now();
insert into contestants set name="MARIAH SHIZ" ,electionID=5 ,categoryID=20 ,code="20FARY10", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY11", createdAt=now();
insert into contestants set name="MIMAH SHAFFIE" ,electionID=5 ,categoryID=20 ,code="20FARY11", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY12", createdAt=now();
insert into contestants set name="BETTY KIRAMATISHO" ,electionID=5 ,categoryID=20 ,code="20FARY12", createdAt=now();
INSERT INTO categories SET name="FEMALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=20 ,code="20FARY13", createdAt=now();
insert into contestants set name="EVELYN WANJIRU" ,electionID=5 ,categoryID=20 ,code="20FARY13", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY1", createdAt=now();
insert into contestants set name="SHADDUF MELODY" ,electionID=5 ,categoryID=21 ,code="21MPARY1", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY2", createdAt=now();
insert into contestants set name="TRESSY K." ,electionID=5 ,categoryID=21 ,code="21MPARY2", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY3", createdAt=now();
insert into contestants set name="MIRIAM WANGUI" ,electionID=5 ,categoryID=21 ,code="21MPARY3", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY4", createdAt=now();
insert into contestants set name="KYOKO DEH" ,electionID=5 ,categoryID=21 ,code="21MPARY4", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY5", createdAt=now();
insert into contestants set name="G-NICE" ,electionID=5 ,categoryID=21 ,code="21MPARY5", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY6", createdAt=now();
insert into contestants set name="RUTH NDIEMA" ,electionID=5 ,categoryID=21 ,code="21MPARY6", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY7", createdAt=now();
insert into contestants set name="MIKE LEBO" ,electionID=5 ,categoryID=21 ,code="21MPARY7", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY8", createdAt=now();
insert into contestants set name="JACKIE MELLY" ,electionID=5 ,categoryID=21 ,code="21MPARY8", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY9", createdAt=now();
insert into contestants set name="MR. CHAIRMAN 254" ,electionID=5 ,categoryID=21 ,code="21MPARY9", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY10", createdAt=now();
insert into contestants set name="SAMANTHA SAETUA" ,electionID=5 ,categoryID=21 ,code="21MPARY10", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY11", createdAt=now();
insert into contestants set name="JOSE KALESON" ,electionID=5 ,categoryID=21 ,code="21MPARY11", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY12", createdAt=now();
insert into contestants set name="DOCHIE" ,electionID=5 ,categoryID=21 ,code="21MPARY12", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY13", createdAt=now();
insert into contestants set name="MERCY SONN" ,electionID=5 ,categoryID=21 ,code="21MPARY13", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY14", createdAt=now();
insert into contestants set name="ELLY GITS" ,electionID=5 ,categoryID=21 ,code="21MPARY14", createdAt=now();
INSERT INTO categories SET name="MOST PROMISING ARTIST OF THE YEAR" ,electionID=5 ,categoryID=21 ,code="21MPARY15", createdAt=now();
insert into contestants set name="JAY DONGA" ,electionID=5 ,categoryID=21 ,code="21MPARY15", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY1", createdAt=now();
insert into contestants set name="TRESSY K.     - NGAI NI NGAI" ,electionID=5 ,categoryID=22 ,code="22TRSY1", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY2", createdAt=now();
insert into contestants set name="MARY NJUGUNA MWAMBA - NDIKARIGANIRWO" ,electionID=5 ,categoryID=22 ,code="22TRSY2", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY3", createdAt=now();
insert into contestants set name="TERRYK.     - THINA" ,electionID=5 ,categoryID=22 ,code="22TRSY3", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY4", createdAt=now();
insert into contestants set name="EUNICE LANG’AT   - KASS KURSET" ,electionID=5 ,categoryID=22 ,code="22TRSY4", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY5", createdAt=now();
insert into contestants set name="SUSAN NDUNG’U   - TUTIGUTHIRA" ,electionID=5 ,categoryID=22 ,code="22TRSY5", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY6", createdAt=now();
insert into contestants set name="LETAIYAN OLEIGERO  - SHUMATA" ,electionID=5 ,categoryID=22 ,code="22TRSY6", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY7", createdAt=now();
insert into contestants set name="MINISTER PAUL GATUNE  - NGAI WA MWENA WAKWA" ,electionID=5 ,categoryID=22 ,code="22TRSY7", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY8", createdAt=now();
insert into contestants set name="ANNE BLESSED   - AHERI NYASAYE" ,electionID=5 ,categoryID=22 ,code="22TRSY8", createdAt=now();
INSERT INTO categories SET name="TRADITIONAL SONGS OF THE YEAR" ,electionID=5 ,categoryID=22 ,code="22TRSY9", createdAt=now();
insert into contestants set name="JOHN MAGERO   - NG’WONO" ,electionID=5 ,categoryID=22 ,code="22TRSY9", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY1", createdAt=now();
insert into contestants set name="DIRECTOR JEREMY  - SMARTLINK RECORDS" ,electionID=5 ,categoryID=23 ,code="23APRY1", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY2", createdAt=now();
insert into contestants set name="PINCHEZ" ,electionID=5 ,categoryID=23 ,code="23APRY2", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY3", createdAt=now();
insert into contestants set name="T-BEAT" ,electionID=5 ,categoryID=23 ,code="23APRY3", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY4", createdAt=now();
insert into contestants set name="SHEM WILLIS" ,electionID=5 ,categoryID=23 ,code="23APRY4", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY5", createdAt=now();
insert into contestants set name="DR. BOIZ   -  FULL ANCHOR MUSIC" ,electionID=5 ,categoryID=23 ,code="23APRY5", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY6", createdAt=now();
insert into contestants set name="PRODUCER SM  - SM RECORDS" ,electionID=5 ,categoryID=23 ,code="23APRY6", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY7", createdAt=now();
insert into contestants set name="WIKY LBDS" ,electionID=5 ,categoryID=23 ,code="23APRY7", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY8", createdAt=now();
insert into contestants set name="MIC RULE" ,electionID=5 ,categoryID=23 ,code="23APRY8", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY9", createdAt=now();
insert into contestants set name="COLO MZIMA" ,electionID=5 ,categoryID=23 ,code="23APRY9", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY10", createdAt=now();
insert into contestants set name="NNOCENT PRODUCER" ,electionID=5 ,categoryID=23 ,code="23APRY10", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY11", createdAt=now();
insert into contestants set name="NATHAN" ,electionID=5 ,categoryID=23 ,code="23APRY11", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY12", createdAt=now();
insert into contestants set name="DENZEL PRODUCER" ,electionID=5 ,categoryID=23 ,code="23APRY12", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY13", createdAt=now();
insert into contestants set name="DICO SOUNDS" ,electionID=5 ,categoryID=23 ,code="23APRY13", createdAt=now();
INSERT INTO categories SET name="AUDIO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=23 ,code="23APRY14", createdAt=now();
insert into contestants set name="PRODUCER DAVID MUHINYA" ,electionID=5 ,categoryID=23 ,code="23APRY14", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY1", createdAt=now();
insert into contestants set name="OLIT VISUALS" ,electionID=5 ,categoryID=24 ,code="24VPRY1", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY2", createdAt=now();
insert into contestants set name="GENDY PRODUCTIONS" ,electionID=5 ,categoryID=24 ,code="24VPRY2", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY3", createdAt=now();
insert into contestants set name="MEDIAPACK FILMS  - PAPA YODEL" ,electionID=5 ,categoryID=24 ,code="24VPRY3", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY4", createdAt=now();
insert into contestants set name="MIKE MIWO BP  - ZIDI MEDIA" ,electionID=5 ,categoryID=24 ,code="24VPRY4", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY5", createdAt=now();
insert into contestants set name="KIJANA WA MUSKOFU  - BORN TO WORSHIP PRO" ,electionID=5 ,categoryID=24 ,code="24VPRY5", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY6", createdAt=now();
insert into contestants set name="SIR MARTIN   - YARIDA MEDIA" ,electionID=5 ,categoryID=24 ,code="24VPRY6", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY7", createdAt=now();
insert into contestants set name="THOMAS TOMSY" ,electionID=5 ,categoryID=24 ,code="24VPRY7", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY8", createdAt=now();
insert into contestants set name="C-SIR    - LACE MEDIA" ,electionID=5 ,categoryID=24 ,code="24VPRY8", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY9", createdAt=now();
insert into contestants set name="SANDEH" ,electionID=5 ,categoryID=24 ,code="24VPRY9", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY10", createdAt=now();
insert into contestants set name="TWISTER BLACK" ,electionID=5 ,categoryID=24 ,code="24VPRY10", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY11", createdAt=now();
insert into contestants set name="DJ GYLO PAINTO  - GEE2 PRODUCTIONS" ,electionID=5 ,categoryID=24 ,code="24VPRY11", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY12", createdAt=now();
insert into contestants set name="JACK JACKSON" ,electionID=5 ,categoryID=24 ,code="24VPRY12", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY13", createdAt=now();
insert into contestants set name="COLLO MZIMA" ,electionID=5 ,categoryID=24 ,code="24VPRY13", createdAt=now();
INSERT INTO categories SET name="VIDEO PRODUCER OF THE YEAR" ,electionID=5 ,categoryID=24 ,code="24VPRY14", createdAt=now();
insert into contestants set name="INNOCENT" ,electionID=5 ,categoryID=24 ,code="24VPRY14", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY1", createdAt=now();
insert into contestants set name="YOUNG STARZZ" ,electionID=5 ,categoryID=25 ,code="25DCRY1", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY2", createdAt=now();
insert into contestants set name="G ENTERTAINMENT DANCE CREW" ,electionID=5 ,categoryID=25 ,code="25DCRY2", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY3", createdAt=now();
insert into contestants set name="ELDORET SCHOOL OF DANCE" ,electionID=5 ,categoryID=25 ,code="25DCRY3", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY4", createdAt=now();
insert into contestants set name="STAPERZ DANCE CREW" ,electionID=5 ,categoryID=25 ,code="25DCRY4", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY5", createdAt=now();
insert into contestants set name="PHD DANCE CREW" ,electionID=5 ,categoryID=25 ,code="25DCRY5", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY6", createdAt=now();
insert into contestants set name="SWAT DANCERS" ,electionID=5 ,categoryID=25 ,code="25DCRY6", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY7", createdAt=now();
insert into contestants set name="TYRANT DANCE CREW" ,electionID=5 ,categoryID=25 ,code="25DCRY7", createdAt=now();
INSERT INTO categories SET name="DANCE CREW OF THE YEAR" ,electionID=5 ,categoryID=25 ,code="25DCRY8", createdAt=now();
insert into contestants set name="REVOLUTIONERZ DANCE CREW" ,electionID=5 ,categoryID=25 ,code="25DCRY8", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY1", createdAt=now();
insert into contestants set name="KENAJ MUSIC" ,electionID=5 ,categoryID=26 ,code="26MARY1", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY2", createdAt=now();
insert into contestants set name="MZALENDO" ,electionID=5 ,categoryID=26 ,code="26MARY2", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY3", createdAt=now();
insert into contestants set name="ANGEL KENYA" ,electionID=5 ,categoryID=26 ,code="26MARY3", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY4", createdAt=now();
insert into contestants set name="HECH KENYA" ,electionID=5 ,categoryID=26 ,code="26MARY4", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY5", createdAt=now();
insert into contestants set name="PAPA TOMASO" ,electionID=5 ,categoryID=26 ,code="26MARY5", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY6", createdAt=now();
insert into contestants set name="OCHI PRAIZE" ,electionID=5 ,categoryID=26 ,code="26MARY6", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY7", createdAt=now();
insert into contestants set name="LENNY LION" ,electionID=5 ,categoryID=26 ,code="26MARY7", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY8", createdAt=now();
insert into contestants set name="JOHN MAGERO" ,electionID=5 ,categoryID=26 ,code="26MARY8", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY9", createdAt=now();
insert into contestants set name="COOPER COOPER" ,electionID=5 ,categoryID=26 ,code="26MARY9", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY10", createdAt=now();
insert into contestants set name="ZAE DE KIM" ,electionID=5 ,categoryID=26 ,code="26MARY10", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY11", createdAt=now();
insert into contestants set name="REV. ANTONY MUSEMBI" ,electionID=5 ,categoryID=26 ,code="26MARY11", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY12", createdAt=now();
insert into contestants set name="FLOYD BELIEVER" ,electionID=5 ,categoryID=26 ,code="26MARY12", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY13", createdAt=now();
insert into contestants set name="Z.B." ,electionID=5 ,categoryID=26 ,code="26MARY13", createdAt=now();
INSERT INTO categories SET name="MALE ARTIST OF THE YEAR" ,electionID=5 ,categoryID=26 ,code="26MARY14S", createdAt=now();
insert into contestants set name="TIMAM EVANS" ,electionID=5 ,categoryID=26 ,code="26MARY14S", createdAt=now();
